name: todo_api
description: An empty Aqueduct application.
version: 0.0.1
author: stable|kernel <jobs@stablekernel.com>

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  uuid: ^2.2.2
  json_annotation: ^3.1.0
  mysql1: ^0.17.1
  get_it: ^5.0.1
  injectable: ^1.0.5
  aqueduct: ^4.0.0-b1

dev_dependencies:
  json_serializable: ^3.5.0
  injectable_generator: ^1.0.6
  build_runner: ^1.10.3
  test: ^1.0.0
  aqueduct_test: ^2.0.0-b1

scripts:
  watch: pub run build_runner watch
  start: aqueduct serve -a 0.0.0.0
